-- =============================================================================
-- Table:   <prefix>_<entity_name_plural>
-- Purpose: <Short description of the table.>
--
-- @author  <Author Name> (<Role>)
-- @created <Month DD, YYYY>
-- @ticket  <TICKET-NUMBER>
-- =============================================================================


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table <prefix>_<entity_name_plural> (
    <entity_name>_id             number generated by default on null as identity (start with 1) primary key not null
  , <column_1>                   varchar2(100 char)
  , <column_2>                   number
  , <fk_entity>_id               number
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint ck_<prefix>_<entity_name_plural>_active_yn check (active_yn in ('Y', 'N'))
  , constraint fk_<entity_name_plural>_<ref_entity_plural> foreign key (<fk_entity>_id) references <prefix>_<ref_entity_plural> (<fk_entity>_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_<prefix>_<entity_name_plural>_active on <prefix>_<entity_name_plural> (active_yn);
create index idx_<prefix>_<entity_name_plural>_<fk_entity> on <prefix>_<entity_name_plural> (<fk_entity>_id);


-- =============================================================================
-- 3. TRIGGERS
-- =============================================================================
create or replace trigger <prefix>_<entity_name_plural>_compound_trg
for insert or update on <prefix>_<entity_name_plural>
compound trigger

  before each row is
  begin
    if updating then
      :new.last_updated_on := localtimestamp;
      :new.last_updated_by := coalesce(
                                sys_context('APEX$SESSION','app_user')
                              , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                              , sys_context('userenv','session_user')
                              );
    end if;
  end before each row;

end <prefix>_<entity_name_plural>_compound_trg;
/


-- =============================================================================
-- 4. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table <prefix>_<entity_name_plural> is ''<Short description of the table.>''';
  execute immediate 'comment on column <prefix>_<entity_name_plural>.<entity_name>_id is ''Unique identifier.''';
  execute immediate 'comment on column <prefix>_<entity_name_plural>.<column_1> is ''<Description.>''';
  execute immediate 'comment on column <prefix>_<entity_name_plural>.<column_2> is ''<Description.>''';
  execute immediate 'comment on column <prefix>_<entity_name_plural>.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
