-- =============================================================================
-- Table:   tf_<table_name>
-- Purpose: <Short description of the table.>
--
-- @author  <Author Name> (<Role>)
-- @created <Month DD, YYYY>
-- @ticket  <TICKET-NUMBER>
-- =============================================================================


-- =============================================================================
-- 1. TABLE
-- =============================================================================
create table tf_<table_name> (
    <table_name>_id              number generated by default on null as identity (start with 1) primary key not null
  , <column_1>                   varchar2(100 char)
  , <column_2>                   number
  , <fk_column>_id              number
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint ck_tf_<table_name>_active_yn check (active_yn in ('Y', 'N'))
  , constraint fk_<table_name>_<ref_table> foreign key (<fk_column>_id) references tf_<ref_table> (<fk_column>_id)
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
create index idx_tf_<table_name>_active on tf_<table_name> (active_yn);
create index idx_tf_<table_name>_<fk_column> on tf_<table_name> (<fk_column>_id);


-- =============================================================================
-- 3. TRIGGERS
-- =============================================================================
create or replace trigger tf_<table_name>_compound_trg
for insert or update on tf_<table_name>
compound trigger

  before each row is
  begin
    if updating then
      :new.last_updated_on := localtimestamp;
      :new.last_updated_by := coalesce(
                                sys_context('APEX$SESSION','app_user')
                              , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                              , sys_context('userenv','session_user')
                              );
    end if;
  end before each row;

end tf_<table_name>_compound_trg;
/


-- =============================================================================
-- 4. COMMENTS
-- =============================================================================
begin
  execute immediate 'comment on table tf_<table_name> is ''<Short description of the table.>''';
  execute immediate 'comment on column tf_<table_name>.<table_name>_id is ''Unique identifier.''';
  execute immediate 'comment on column tf_<table_name>.<column_1> is ''<Description.>''';
  execute immediate 'comment on column tf_<table_name>.<column_2> is ''<Description.>''';
  execute immediate 'comment on column tf_<table_name>.active_yn is ''Soft-delete flag: Y = active, N = inactive.''';
end;
/
